### ISSUE TITLE
Rate limited running `fastly/compute-actions/setup@v2`

### ISSUE THREAD

**Issue by ccouzens** [fastly/compute-actions#20]
We had a failed deploy caused by a rate limiting error:

```
Error: Unable to fetch the requested release (latest): API rate limit exceeded for 20.39.47.73. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

I presume Github Actions runner was rate limited downloading the `fastly` package from Github.

![image](https://user-images.githubusercontent.com/241046/180196558-85330df7-fb74-4f93-95b1-95074a660f84.png)

The [IP Address](https://www.speedguide.net/ip/20.39.47.73) is Microsoft's and presumably the IP of the Github runner.

**Comment by JakeChampion** [comment]
@ccouzens That usually means the action was not supplied a GitHub token to use for the API requests.

Could you try this and see if it works for you?
```yml
 - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by JakeChampion** [comment]
@ccouzens did using a GitHub token resolve the issue for you?

**Comment by ccouzens** [comment]
Hi, we have always had a github token setup in this workflow.

We haven't seen the issue again, so I'm dismissing it as a blip and closing the issue.

Thank you for your time.

**Comment by platy** [comment]
@JakeChampion Did you mean to suggest adding a fastly token here rather than a github token here. This looks like a rate limit from fastly rather than a rate limit from github

```yaml
    - uses: fastly/compute-actions/deploy@v2
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
```

**Comment by JakeChampion** [comment]
I did not, this is a GitHub rate limit and is solved by providing the token from the running action like so:
```yaml
 - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```
