### ISSUE TITLE
support for --version flag in deploy action

### ISSUE THREAD

**Issue by nodirnasirov** [fastly/compute-actions#24]
In my cicd pipeline I am using deploy action, but I need it to deploy by cloning active version, not the latest one. CLI command for it would be `fastly compute deploy --version=active`. Unfortunately flag is missing in fastly deploy github action.
Current step in my yaml:
```
- name: Deploy Compute@Edge Package
        uses: fastly/compute-actions/deploy@v2
        with:
          service_id: "my-service-id"
          comment: "foo bar"
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
```
Would be great to have:
```
- name: Deploy Compute@Edge Package
        uses: fastly/compute-actions/deploy@v2
        with:
          service_id: "my-service-id"
          version: "active"
          comment: "foo bar"
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
```
