### ISSUE TITLE
"Provided cli_version () is not a valid SemVer string"

### ISSUE THREAD

**Issue by kpeters-cbsi** [fastly/compute-actions#28]
When using the recommended Cargo-based workflow from the README, I get the following output:

```
FASTLY_API_TOKEN=XXXX act -j deploy --env FASTLY_API_TOKEN -W .github/workflows/deploy-cate.yml
Provide value for 'AWS_ACCESS_KEY_ID': 
Provide value for 'AWS_SECRET_ACCESS_KEY': 
[Deploy Application/deploy] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
[Deploy Application/deploy]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false
[Deploy Application/deploy]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Deploy Application/deploy]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Deploy Application/deploy]   ☁  git clone 'https://github.com/actions-rs/toolchain' # ref=v1
[Deploy Application/deploy]   ☁  git clone 'https://github.com/fastly/compute-actions' # ref=v2
[Deploy Application/deploy] ⭐ Run Pre Deploy to Compute@Edge
[Deploy Application/deploy]   🐳  docker cp src=/Users/cpete0624/.cache/act/fastly-compute-actions@v2/ dst=/var/run/act/actions/fastly-compute-actions@v2/
[Deploy Application/deploy] close /var/folders/99/_cljf5rd63xcqkklkrct4v9h0000gn/T/act2201414501: file already closed
[Deploy Application/deploy]   🐳  docker exec cmd=[node /var/run/act/actions/fastly-compute-actions@v2/setup/index.js] user= workdir=
[Deploy Application/deploy]   ❗  ::error::The provided cli_version () is not a valid SemVer string.
[Deploy Application/deploy]   ❗  ::error::
[Deploy Application/deploy]   ❌  Failure - Pre Deploy to Compute@Edge
[Deploy Application/deploy] 🏁  Job succeeded
Error: exitcode '1': failure
```

Workflow:
```
name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.54.0 # current Rust toolchain for Compute@Edge
          target: wasm32-wasi # WebAssembly target

    - name: Deploy to Compute@Edge
      uses: fastly/compute-actions@v2
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
```
